# -*- coding: utf-8 -*-
"""deepface22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BWCLUWEBSD2ft7jQ7SHBmCyzPb-p_rR-
"""

pip install deepface

from deepface import DeepFace
#model = load_model('model.h5')
#demography = DeepFace.analyze("/content/drive/My Drive/h.jpg") #passing nothing as 2nd argument will find everything
demography = DeepFace.analyze("sad.jpg", ['age', 'gender',  'emotion']) #identical to the line above
#demographies = DeepFace.analyze(["img1.jpg", "img2.jpg", "img3.jpg"]) #analyzing multiple faces same time
print('\n', "-------------------")
print("Age: ", demography["age"])
print("Gender: ", demography["gender"])
print("Emotion: ", demography["dominant_emotion"])
#print("Race: ", demography["dominant_race"])