# incoming inputs
INPUT_MODE_CHANGE = 0

MODE_CHANGE_OCR = 1
MODE_CHANGE_SCENE = 2
MODE_CHANGE_FACE_RECOGNITION = 3
MODE_CHANGE_EMOTIONS = 4
MODE_CHANGE_OBJECT_DETECTION = 5

# outgoing outputs
OUTPUT_RESULT = 0
RESULT_OCR = 1
RESULT_SCENE = 2
RESULT_FACE_RECOGNITION = 3
RESULT_EMOTIONS = 4
RESULT_OBJECT_DETECTION = 5
